#!/bin/sh

mount -a

mdev -s

uptime

echo ""
echo "        .M"    
echo "       MMMM"   
echo "      7MM  M"  
echo "      MM   M." 
echo "      M.   M "
echo "      M: .MM."
echo "       MMMM."
echo "      ~MMM .##############################################"
echo "     MMM=                                                #"
echo "   MMMM D        Welcome on mini AirPlay OS              #"
echo "  MMM.. M  .               by Mras2an                    #"
echo " MM8 .MMMMMMM.                2014                       #"
echo ".MM..MM Z.  MM ###########################################"
echo ".MM  M.  M  .M"
echo " MM   M: M  .M."
echo "  MM.   .M .M."
echo "   ..MMMMM="
echo "         .M"
echo "  ,MMM   .M"
echo "  MMMM   .M"
echo "   M     M "
echo "   ..8M:."

